version: '3'

# https://github.com/abakonski/docker-compose-flask

services:

  # mydb:
  #   build:
  #     context: ./mydb
  #   container_name: mydb
  #   ports:
  #     - 5001:5001

  web:
    # restart: always
    build:
      context: ./web
    ports:
      - 8000:8000
    command: gunicorn app.app:app --workers 4 --name app -b 0.0.0.0:8000
    volumes:
      - ./database_clients_camera:/usr/src/database_clients_camera
    # depends_on:
    #   - mydb

  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 81:443
    links:
      - web

  ecoclient:
    build:
      context: ./ecoclient
    # ports:
    #   - 5555:5555
    depends_on:
      - web

