version: '3'

# first copy into ecoclient the folder package? int the shared_folder in Project/EcoVision dir.
# it was obtained from the docker container ecovision in this latter dir (it compiled and created packages and shared it with me the host)
# cp -r ../../EcoVision/shared_folder/package_ecovision ./ecoclient

# docker-compose build web
# docker-compose build nginx   # for VM
# docker-compose build ecoclient

# docker-compose up web -d
# docker-compose up nginx -d  # for VM
# docker run -t -d -v $PWD/ecoclient/shared_folder:/usr/src/app/shared_folder --name ecoclient ecoclient_ecoclient
# docker exec -it ecoclient bash

# https://github.com/abakonski/docker-compose-flask
services:

  # mydb:
  #   build:
  #     context: ./mydb
  #   container_name: mydb
  #   ports:
  #     - 5001:5001

  web:
    # restart: always
    build:
      context: ./web
    ports:
      - 8000:8000
    command: gunicorn app.app:app --workers 4 --name app -b 0.0.0.0:8000
    volumes:
      - ./database_clients_camera:/usr/src/database_clients_camera
    # depends_on:
    #   - mydb

  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 81:443
    links:
      - web

  ecoclient:
    build:
      context: ./ecoclient
    container_name: ecoclient
    depends_on:
      - web

  # see errors in dockerfile
  # ecoclient:
  #   build:
  #     context: ./ecoclient
  #   depends_on:
  #     - web
  #   # command:
  #   #   - python3 manage.py runserver

